# Generated by Django 5.1.5 on 2025-02-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10)),
                ('module_name', models.CharField(max_length=100)),
                ('cw1', models.IntegerField()),
                ('cw2', models.IntegerField()),
                ('cw3', models.IntegerField()),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
